name = "memedam"
compatibility_date = "2024-01-01"

[pages_build_output_dir]
directory = "dist"

[build]
command = "npm run build"

[build.environment]
NODE_VERSION = "22.16.0"
NODE_ENV = "production"

[env.production]
name = "memedam"